server:
  port: 9000

spring:
  application:
    name: building-manager
  cloud:
    nacos:
      discovery:
        server-addr: 112.74.42.138:8848
  profiles:
    active: dev
dubbo:
  scan:
    base-packages: com.xiaojun.buildingmanager.service.impl
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://112.74.42.138:8848
